import type { Dimension, DimensionKey, Question } from "./types";

export const dimensionOrder: DimensionKey[] = [
  "collaboration",
  "trust",
  "liability",
  "propagation",
];

export const dimensions: Record<DimensionKey, Dimension> = {
  collaboration: {
    key: "collaboration",
    label: "协作态度",
    left: "独行侠",
    right: "布道者",
    leftDesc: "更强调自由传承与开源延续",
    rightDesc: "更强调开放使用与广泛采用",
  },
  trust: {
    key: "trust",
    label: "信任模式",
    left: "审计员",
    right: "乐捐者",
    leftDesc: "更在意署名、可追溯性与边界说明",
    rightDesc: "更在意流通效率与低门槛复用",
  },
  liability: {
    key: "liability",
    label: "责任边界",
    left: "盾牌手",
    right: "冒险家",
    leftDesc: "更看重免责条款、风险隔离与责任边界",
    rightDesc: "更接受少约束、重实践的发布方式",
  },
  propagation: {
    key: "propagation",
    label: "传播执念",
    left: "传教士",
    right: "实用派",
    leftDesc: "更希望改动持续回流并保持同类开放",
    rightDesc: "更接受与闭源、商业生态自由混搭",
  },
};

export const questions: Question[] = [
  // collaboration (1-8)
  {
    id: 1,
    dimension: "collaboration",
    text: "你写的核心库被 fork 后改造成闭源 SaaS 产品，你更能接受哪种处理方式？",
    leftAnswer: "必须开源改动",
    rightAnswer: "闭源也能接受",
  },
  {
    id: 2,
    dimension: "collaboration",
    text: "某团队把你的项目改得面目全非后重新发布，你会更希望他们：",
    leftAnswer: "注明出处为妥",
    rightAnswer: "改了就是他们的",
  },
  {
    id: 3,
    dimension: "collaboration",
    text: "如果别人把你的代码打包进商业桌面软件，你对「是否必须公开修改」更偏向：",
    leftAnswer: "必须公开修改",
    rightAnswer: "无需公开",
  },
  {
    id: 4,
    dimension: "collaboration",
    text: "你更喜欢自己的项目成为「自由传承的公共基础设施」，还是「谁都能拿来即用的积木」？",
    leftAnswer: "自由传承基建设施",
    rightAnswer: "即用积木",
  },
  {
    id: 5,
    dimension: "collaboration",
    text: "当社区成员基于你的项目做大型二次开发时，你更希望他们：",
    leftAnswer: "回馈社区",
    rightAnswer: "自行决定",
  },
  {
    id: 6,
    dimension: "collaboration",
    text: "你怎么看「拿来主义」式复用你的代码而不回传改动？",
    leftAnswer: "应当回传改动",
    rightAnswer: "拿走就用挺好",
  },
  {
    id: 7,
    dimension: "collaboration",
    text: "如果你的工具链被嵌入某个企业私有平台，你更倾向于：",
    leftAnswer: "必须开源平台改动",
    rightAnswer: "企业自用可以",
  },
  {
    id: 8,
    dimension: "collaboration",
    text: "你理想中的开源协作，更接近「保证所有衍生成果继续开放」还是「先让使用范围最大化」？",
    leftAnswer: "衍生成果继续开放",
    rightAnswer: "使用范围最大化",
  },
  // trust (9-16)
  {
    id: 9,
    dimension: "trust",
    text: "别人用了你的代码却没在 README 里提到你，你会更在意：",
    leftAnswer: "介意不署名",
    rightAnswer: "代码有用就好",
  },
  {
    id: 10,
    dimension: "trust",
    text: "项目被大量转发和搬运时，你更希望保留的东西是：",
    leftAnswer: "保留作者信息",
    rightAnswer: "保留使用自由",
  },
  {
    id: 11,
    dimension: "trust",
    text: "如果有人删掉作者信息但保留代码，你的第一反应更接近：",
    leftAnswer: "删名字不能忍",
    rightAnswer: "代码可用就行",
  },
  {
    id: 12,
    dimension: "trust",
    text: "你更认同「署名是基本尊重」，还是「降低使用门槛更重要」？",
    leftAnswer: "署名是基本尊重",
    rightAnswer: "门槛低更重要",
  },
  {
    id: 13,
    dimension: "trust",
    text: "对于第三方分发你的代码时附不附原始声明，你的态度更偏向：",
    leftAnswer: "原始声明应保留",
    rightAnswer: "附不附随他",
  },
  {
    id: 14,
    dimension: "trust",
    text: "如果别人拿你的项目做教材或课程，你更希望他们：",
    leftAnswer: "注明来源",
    rightAnswer: "不用注明",
  },
  {
    id: 15,
    dimension: "trust",
    text: "看到别人引用你的仓库却只说「来自互联网」，你更容易觉得：",
    leftAnswer: "觉得被冒犯",
    rightAnswer: "无所谓",
  },
  {
    id: 16,
    dimension: "trust",
    text: "在版权声明和传播效率之间，你通常更优先考虑：",
    leftAnswer: "保留版权声明",
    rightAnswer: "提升传播效率",
  },
  // liability (17-24)
  {
    id: 17,
    dimension: "liability",
    text: "你的库被用于生产环境并引发事故时，你更希望许可证：",
    leftAnswer: "免责写清楚",
    rightAnswer: "用了就别找我",
  },
  {
    id: 18,
    dimension: "liability",
    text: "面对「免责声明要不要写得很硬」这个问题，你通常倾向：",
    leftAnswer: "免责声明要硬",
    rightAnswer: "差不多就行",
  },
  {
    id: 19,
    dimension: "liability",
    text: "如果别人因为误用你的代码导致损失，你觉得许可证最该强调：",
    leftAnswer: "免责保护作者",
    rightAnswer: "默认各自承担",
  },
  {
    id: 20,
    dimension: "liability",
    text: "你更喜欢「风险边界写清楚」，还是「默认大家自己承担实践风险」的氛围？",
    leftAnswer: "边界写清楚",
    rightAnswer: "实践自己负责",
  },
  {
    id: 21,
    dimension: "liability",
    text: "别人问你为什么 LICENSE 里有一大段免责文字时，你更可能回答：",
    leftAnswer: "防患于未然",
    rightAnswer: "太长也没用",
  },
  {
    id: 22,
    dimension: "liability",
    text: "你对「许可证越短越好」这件事，在责任条款上更偏向：",
    leftAnswer: "免责部分不能省",
    rightAnswer: "越短越好",
  },
  {
    id: 23,
    dimension: "liability",
    text: "如果你的项目可能涉及专利或合规风险，你更希望：",
    leftAnswer: "许可证涵盖专利",
    rightAnswer: "不用太复杂",
  },
  {
    id: 24,
    dimension: "liability",
    text: "从法律视角看，你更想把许可证写成：",
    leftAnswer: "严谨的法律文书",
    rightAnswer: "简短的声明",
  },
  // propagation (25-32)
  {
    id: 25,
    dimension: "propagation",
    text: "你更希望别人修改你的代码后继续使用同类开放许可证，还是随他们挑选新协议？",
    leftAnswer: "必须同类开放",
    rightAnswer: "随他们选",
  },
  {
    id: 26,
    dimension: "propagation",
    text: "看到自己的项目被整合进闭源产品时，你更可能在意：",
    leftAnswer: "闭源不合理念",
    rightAnswer: "整合也是好事",
  },
  {
    id: 27,
    dimension: "propagation",
    text: "如果改动后的版本只在网络服务中运行，不对外分发，你更希望：",
    leftAnswer: "网络服务也开源",
    rightAnswer: "不分发就不用",
  },
  {
    id: 28,
    dimension: "propagation",
    text: "对「衍生作品必须继续开放」这件事，你的直觉更接近：",
    leftAnswer: "必须继续开放",
    rightAnswer: "不必强求",
  },
  {
    id: 29,
    dimension: "propagation",
    text: "你更支持「把改动还给社区」，还是「先让商业采用没有顾虑」？",
    leftAnswer: "改动还给社区",
    rightAnswer: "商业采用优先",
  },
  {
    id: 30,
    dimension: "propagation",
    text: "如果你的代码被链接进大型闭源系统，你更希望许可证：",
    leftAnswer: "必须保持开放",
    rightAnswer: "链接可闭源",
  },
  {
    id: 31,
    dimension: "propagation",
    text: "你更赞同「自由必须会传染」，还是「兼容现实生态更重要」？",
    leftAnswer: "自由必须传染",
    rightAnswer: "兼容更重要",
  },
  {
    id: 32,
    dimension: "propagation",
    text: "对于二次分发者是否必须保持相同开放力度，你整体态度更偏向：",
    leftAnswer: "必须保持开放",
    rightAnswer: "灵活对待就好",
  },
];
