import type { Dimension, DimensionKey, Question } from "./types";

export const dimensionOrder: DimensionKey[] = [
  "collaboration",
  "trust",
  "liability",
  "propagation",
];

export const dimensions: Record<DimensionKey, Dimension> = {
  collaboration: {
    key: "collaboration",
    label: "协作态度",
    labelEn: "Collaboration",
    abbr: "COL",
    left: "独行侠",
    right: "布道者",
    leftDesc: "更强调自由传承与开源延续",
    rightDesc: "更强调开放使用与广泛采用",
  },
  trust: {
    key: "trust",
    label: "信任模式",
    labelEn: "Trust",
    abbr: "TRU",
    left: "审计员",
    right: "乐捐者",
    leftDesc: "更在意署名、可追溯性与边界说明",
    rightDesc: "更在意流通效率与低门槛复用",
  },
  liability: {
    key: "liability",
    label: "责任边界",
    labelEn: "Liability",
    abbr: "LIA",
    left: "盾牌手",
    right: "冒险家",
    leftDesc: "更看重免责条款、风险隔离与责任边界",
    rightDesc: "更接受少约束、重实践的发布方式",
  },
  propagation: {
    key: "propagation",
    label: "传播执念",
    labelEn: "Propagation",
    abbr: "PRO",
    left: "传教士",
    right: "实用派",
    leftDesc: "更希望改动持续回流并保持同类开放",
    rightDesc: "更接受与闭源、商业生态自由混搭",
  },
};

export const questions: Question[] = [
  // collaboration (1-8)
  {
    id: 1,
    dimension: "collaboration",
    text: "你的核心库被 fork 后改成了闭源 SaaS，你觉得对方应该：",
    leftAnswer: "必须把改动也开源",
    rightAnswer: "闭源也没关系",
  },
  {
    id: 2,
    dimension: "collaboration",
    text: "有人把你的项目大改一通后重新发布，你更希望他们：",
    leftAnswer: "把改动回传给社区",
    rightAnswer: "改了就改了，随他们",
  },
  {
    id: 3,
    dimension: "collaboration",
    text: "别人把你的代码打包进了商业桌面软件，你对公开修改这件事：",
    leftAnswer: "改了什么必须公开",
    rightAnswer: "不用公开",
  },
  {
    id: 4,
    dimension: "collaboration",
    text: "你希望自己的项目更像哪种角色？",
    leftAnswer: "公共基础设施，自由传承",
    rightAnswer: "通用积木，谁都能用",
  },
  {
    id: 5,
    dimension: "collaboration",
    text: "社区有人基于你的项目做了大型二次开发，你希望他们：",
    leftAnswer: "把成果回馈社区",
    rightAnswer: "自己留着也行",
  },
  {
    id: 6,
    dimension: "collaboration",
    text: "有人拿你的代码去用，但一个改动也没还回来，你怎么看？",
    leftAnswer: "多少该回传一点",
    rightAnswer: "能用就行，不还也没事",
  },
  {
    id: 7,
    dimension: "collaboration",
    text: "你的工具被集成到了某企业的私有系统里，你更倾向于：",
    leftAnswer: "企业得开源他们的改动",
    rightAnswer: "内部用就不用开源",
  },
  {
    id: 8,
    dimension: "collaboration",
    text: "你理想中的开源生态，更接近以下哪种图景？",
    leftAnswer: "一切衍生都保持开放",
    rightAnswer: "让代码被用得越广越好",
  },
  // trust (9-16)
  {
    id: 9,
    dimension: "trust",
    text: "别人用了你的代码，但 README 里一个字都没提你，你第一反应是：",
    leftAnswer: "好歹提一下名字吧",
    rightAnswer: "代码有用就行，无所谓",
  },
  {
    id: 10,
    dimension: "trust",
    text: "项目被到处转发搬运时，你更在意什么被保留？",
    leftAnswer: "原作者信息不能丢",
    rightAnswer: "大家能用上就行",
  },
  {
    id: 11,
    dimension: "trust",
    text: "有人把你的代码里作者信息全删了但保留了代码本身，你更接近哪种感受？",
    leftAnswer: "删名字不太尊重人",
    rightAnswer: "代码还在用就行",
  },
  {
    id: 12,
    dimension: "trust",
    text: "你更认同哪句话？",
    leftAnswer: "署名是对创作者的基本尊重",
    rightAnswer: "降低门槛比署名更重要",
  },
  {
    id: 13,
    dimension: "trust",
    text: "第三方分发你代码的时候，你觉得原始声明应该：",
    leftAnswer: "必须一起附上",
    rightAnswer: "附不附都行",
  },
  {
    id: 14,
    dimension: "trust",
    text: "别人拿你的项目做教材或课程，你希望他们：",
    leftAnswer: "注明代码来源",
    rightAnswer: "不用特意注明",
  },
  {
    id: 15,
    dimension: "trust",
    text: "看到有人引用你的仓库，只说「来自互联网」，你更可能想：",
    leftAnswer: "提一下我的名字很难吗",
    rightAnswer: "不重要，用就好",
  },
  {
    id: 16,
    dimension: "trust",
    text: "在版权保护和传播效率之间，你通常更倾向于：",
    leftAnswer: "保留版权声明",
    rightAnswer: "先保证传播够快",
  },
  // liability (17-24)
  {
    id: 17,
    dimension: "liability",
    text: "你的库被用在生产环境里出了事故，你希望许可证能：",
    leftAnswer: "把免责条款写得明明白白",
    rightAnswer: "用了就别来找我",
  },
  {
    id: 18,
    dimension: "liability",
    text: "有人问你免责声明写那么硬核干嘛，你更可能回答：",
    leftAnswer: "预防万一，不写清楚不放心",
    rightAnswer: "意思到了就行，不用太较真",
  },
  {
    id: 19,
    dimension: "liability",
    text: "如果别人误用了你的代码导致损失，你觉得许可证最该强调：",
    leftAnswer: "保护作者不被追责",
    rightAnswer: "风险大家默认自己扛",
  },
  {
    id: 20,
    dimension: "liability",
    text: "你更偏好哪种责任氛围？",
    leftAnswer: "把风险边界都划清楚",
    rightAnswer: "用代码就有风险，自己担",
  },
  {
    id: 21,
    dimension: "liability",
    text: "别人吐槽你 LICENSE 里免责文字太长，你会怎么回？",
    leftAnswer: "长点放心，怕说不清楚",
    rightAnswer: "确实不用写那么多",
  },
  {
    id: 22,
    dimension: "liability",
    text: "在「许可证越短越好」这件事上，你对免责条款的态度是：",
    leftAnswer: "免责不能省，再短也得写",
    rightAnswer: "整体越短越好，免责也是",
  },
  {
    id: 23,
    dimension: "liability",
    text: "你的项目涉及专利或合规风险时，你更希望：",
    leftAnswer: "许可证把专利条款写清楚",
    rightAnswer: "别搞太复杂",
  },
  {
    id: 24,
    dimension: "liability",
    text: "从法律风格上看，你更想把许可证写成：",
    leftAnswer: "严谨全面的法律文书",
    rightAnswer: "简单直白的声明",
  },
  // propagation (25-32)
  {
    id: 25,
    dimension: "propagation",
    text: "别人改完你的代码后，你希望他们用什么许可证发布？",
    leftAnswer: "必须用同类开放许可证",
    rightAnswer: "用什么都行，他们自己定",
  },
  {
    id: 26,
    dimension: "propagation",
    text: "自己的项目被整合进闭源产品，你的感受更接近：",
    leftAnswer: "闭源有点违背我的理念",
    rightAnswer: "能被整合说明有价值",
  },
  {
    id: 27,
    dimension: "propagation",
    text: "改动后的版本只在网上跑、不对外发，你觉得应该：",
    leftAnswer: "网络服务也得开源改动",
    rightAnswer: "不分发就不用开源",
  },
  {
    id: 28,
    dimension: "propagation",
    text: "对「衍生作品必须继续开放」这个主张，你更偏向：",
    leftAnswer: "确实应该继续开放",
    rightAnswer: "不必强求",
  },
  {
    id: 29,
    dimension: "propagation",
    text: "你更希望开源生态往哪个方向走？",
    leftAnswer: "改动回流，保持链条开放",
    rightAnswer: "商业采用零顾虑，先繁荣",
  },
  {
    id: 30,
    dimension: "propagation",
    text: "你的代码被链接进大型闭源系统，你希望许可证怎么说？",
    leftAnswer: "链接场景也必须开放",
    rightAnswer: "链接可以闭源，不用管",
  },
  {
    id: 31,
    dimension: "propagation",
    text: "在「自由传染力」和「兼容性」之间，你更看重：",
    leftAnswer: "自由必须会传染",
    rightAnswer: "兼容现实生态更重要",
  },
  {
    id: 32,
    dimension: "propagation",
    text: "对于二次分发者是否必须保持相同的开放力度，你整体态度是：",
    leftAnswer: "必须保持一致",
    rightAnswer: "灵活对待，看情况",
  },
];
